# Generated by Django 5.0.1 on 2024-01-18 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_querymodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='querymodel',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
